# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: pgweb
version: "0.2.0"
slug: pgweb
description: Web-based PostgreSQL database browser
url: "https://github.com/bjeanes/ha-apps/tree/main/pgweb"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8081
panel_icon: mdi:database-edit-outline
stage: experimental
options:
  db: "postgresql://postgres:homeassistant@77b2833f-timescaledb/homeassistant?sslmode=disable"
schema:
  db: "url"
image: "ghcr.io/bjeanes/ha-app-pgweb"
